const ROOT_PRODUCTS = document.getElementById('products')
const ROOT_HEADER = document.getElementById('header')
const ROOT_CARD = document.getElementById('card')
const ROOT_SPINNER = document.getElementById('spinner')
const ROOT_ERROR = document.getElementById('error')
